sedit  's/skstream.h/skstream\/skstream.h/'  src/Connection.cpp      &&
sedit  's/skstream.h/skstream\/skstream.h/'  src/MetaQuery.cpp       &&
sedit  's/skstream.h/skstream\/skstream.h/'  src/BaseConnection.cpp  &&
sedit  's/skstream.h/skstream\/skstream.h/'  src/Metaserver.cpp      &&
default_build
