(

  I_DIR="/usr/share/games/forge"   &&
  mkdir  -p  ${I_DIR}              &&
  cd  ..                           &&
  cp  -r  media  ${I_DIR}          &&
  chown  -R  root.games  ${I_DIR}  &&
  cd  -

)  >  ${C_FIFO}  2>&1
