OPTS="$BZFLAG_THREADS   \
      $BZFLAG_ADMIN     \
      $BZFLAG_CLIENT    \
      $BZFLAG_ROBOTS    \
      $BZFLAG_SNAPPING  \
      $BZFLAG_CURL      \
      $OPTS"            &&

./autogen.sh  &&

default_games_build
