#!/bin/sh
#
# Cube client binary loader
#
# Written for Source Mage GNU/Linux by Eric Sandall <sandalle@sourcemage.org>
# Copyright (C) Source mage GNU/Linux 2004
# Licensed under the GPL
#

cd  /usr/share/games/cube  &&
./bin/cube_client_bin  $*
