OPTS+=" -DFG_DATA_DIR=${TRACK_ROOT}/usr/share/games/flightgear" &&
OPTS+=" -DWITH_FGPANEL=off"                                     &&

glselect mesa                                                   &&
cmake_build
