export   CPPFLAGS="$CPPFLAGS -I/usr/include/Atlas-C++-0.4/" &&
patch  -p1  <  ${SCRIPT_DIRECTORY}/skstream-0.3.patch       &&
patch  -p1  <  ${SCRIPT_DIRECTORY}/is_ready.patch       &&

default_build
