OPTS+=" -DBINDIR=$INSTALL_ROOT/usr/games"                  &&
OPTS+=" -DLIBDIR=$INSTALL_ROOT/usr/lib"                    &&
OPTS+=" -DDATADIR=$INSTALL_ROOT/usr/share/games/nitrohack" &&
OPTS+=" -DSHELLDIR=$INSTALL_ROOT/usr/games"                &&
cmake_build
