(

  prepare_install                            &&
  mkdir  -p  /usr/share/${SPELL}/${VERSION}  &&
  cd  /usr/share/${SPELL}/${VERSION}         &&
  unpack  ${SOURCE}  ${MD5[0]}

)  >  ${C_FIFO}  2>&1
