if  check_if_xorg_modular_libs  ;  then
  OPTS="$OPTS --x-libraries=${TRACK_ROOT}/usr/lib"
fi                                                 &&

make_single         &&
default_games_build &&
make_normal
