(

  C_DIR="/usr/share/cal3d"
  install  -d  -m  755  $C_DIR/cally               &&
  install  -d  -m  755  $C_DIR/paladin             &&
  install  -d  -m  755  $C_DIR/skeleton            &&
  install  -m  644  cally/*.*  $C_DIR/cally        &&
  install  -m  644  paladin/*.*  $C_DIR/paladin    &&
  install  -m  644  skeleton/*.*  $C_DIR/skeleton

)  >  $C_FIFO  2>&1
