patch -p0 < ${SCRIPT_DIRECTORY}/Makefile.in1.patch              &&
patch -p0 < ${SCRIPT_DIRECTORY}/place.cpp.patch                 &&
patch -p0 < ${SCRIPT_DIRECTORY}/configfile.cpp.patch            &&
patch -p0 < ${SCRIPT_DIRECTORY}/limage.cpp.patch                &&
#patch -p0 < ${SCRIPT_DIRECTORY}/lotrmap.cpp.patch               &&
#patch -p0 < ${SCRIPT_DIRECTORY}/middleearth2_c.jpg.maprc.patch  &&
patch -p0 < ${SCRIPT_DIRECTORY}/Makefile.in2.patch              &&

default_build

