#!/bin/sh

mkdir -p ${HOME}/.vegastrike
cd ${HOME}/.vegastrike
#if [ -e save.4.x.txt ] ; then
#	touch save.4.x.txt;
#else
#	echo "default"> save.4.x.txt ;
#	mkdir -p ${HOME}/.vegastrike/save
#	cp save.4.x.txt save/
#fi
cp /usr/share/games/vegastrike/0.5.0/{setup.config,.vegastrike-0.5.0/*.m3u,vegastrike.config} .
/usr/games/vssetup

