# factor is provided by coreutils
rm -rf factor/                                    &&
# fortune is from ... fortune
rm -rf fortune/                                   &&
yes "" | ./configure                              &&
make
