CFLAGS=${CFLAGS/-fPIC}                    &&
CFLAGS=${CFLAGS/-DPIC}                    &&
CXXFLAGS=${CXXFLAGS/-fPIC}                &&
CXXFLAGS=${CXXFLAGS/-DPIC}                &&
default_games_build
