./configure --prefix=$INSTALL_ROOT/usr              \
        --man-prefix=$INSTALL_ROOT/usr/share/man    \
       --data-prefix=$INSTALL_ROOT/usr/share/games  \
                     $OPTS                          &&
make
