./configure             $OPTS                                                                &&
sedit  "s:prefix\s*=\s*/usr/local:prefix=/usr:"                                    Makefile  &&
sedit  "s:bindir\s*=\s*/usr/local/bin:bindir=/usr/games:"                          Makefile  &&
sedit  "s:mandir\s*=\s*/usr/local/man:mandir=/usr/share/man:"                      Makefile  &&
sedit  "s:datadir\s*=\s*/usr/local/share/eboard:datadir=/usr/share/games/eboard:"  Makefile  &&
make
