# Nice and easy compilation
make build_release                                                 &&

cd release*                                                        &&

# The game*.so has to be in the baseq2 dir
mkdir -p baseq2                                                    &&
mv game*.so baseq2
