# This is a bit ugly, but works until upstream is
# fixed or patched.
OPTS="$OPTS \
  --prefix=${INSTALL_ROOT}/usr \
  --datadir=${INSTALL_ROOT}/usr/share \
  --localstatedir=${INSTALL_ROOT}/var/games" &&
# default_games_build fails terribly.  Don't use it!
default_build
