(

  ./configure  --prefix=/usr           \
               --bindir=/usr/games     \
               --mandir=/usr/share/man &&
  make                              &&
  prepare_install                   &&
  make    install

) > $C_FIFO 2>&1
