OPTS="$CELESTIA_XINERAMA                                            \
      $CELESTIA_FINAL                                               \
      --with-gconf-schema-file-dir=$INSTALL_ROOT/etc/gconf/schemas  \
      --disable-debug                                               \
      $OPTS"                                                        &&

default_build
