OPTS="$OPTS --prefix-dir=${INSTALL_ROOT}/usr \
      --binary-dir=/games \
      --data-dir=/share/games/openttd \
      --man-dir=/share/man" &&
./configure $OPTS                                                      &&
make
