#!/bin/sh

if ! [ -d $HOME/.openttd ]; then
  mkdir -p $HOME/.openttd
fi &&
if ! [ -d $HOME/.openttd/scenario ]; then
  cp -r /usr/share/games/openttd/scenario $HOME/.openttd
fi &&
if ! [ -d $HOME/.openttd/autosave ]; then
  mkdir -p $HOME/.openttd/autosave
fi &&
/usr/libexec/openttd "${@}"
