#!/bin/sh
#
# Sauerbraten client binary loader
#
# Written for Source Mage GNU/Linux by Eric Sandall <sandalle@sourcemage.org>
# Copyright (C) Source mage GNU/Linux 2005
# Licensed under the GPL
#

cd  /usr/share/games/sauerbraten  &&
exec  ./bin/sauerbraten_client_bin  $*
