# read the vars
. ${INSTALL_ROOT}/etc/profile.d/crystalspace.sh                                &&
cp ${INSTALL_ROOT}$CRYSTAL/bin/cs-config .                                     &&
make                                                                             

