./configure --prefix="$INSTALL_ROOT"/usr                 \
            --bindir="$INSTALL_ROOT"/usr/games           \
           --datadir="$INSTALL_ROOT"/usr/share/games     \
    --enable-release $UFOAI_OPTS $OPTS &&
make
