OPTS="$OPTS -DQt5Widgets_DIR=$TRACK_ROOT/opt/qt5/lib/cmake/Qt5Widgets" &&
OPTS="$OPTS -DQt5Network_DIR=$TRACK_ROOT/opt/qt5/lib/cmake/Qt5Network" &&
OPTS="$OPTS -DQt5OpenGL_DIR=$TRACK_ROOT//opt/qt5/lib/cmake/Qt5OpenGL"  &&
qt5_cmake_build
