NOCONFIGURE="NO"  ./autogen.sh  &&

OPTS="          $OPTS                             \
       --bindir=${INSTALL_ROOT}/usr/games         \
      --datadir=${INSTALL_ROOT}/usr/share/games"  &&

default_build
