sedit  "s/MesaGL/GL/g"                   Makefile       &&
sedit  "s/\/local//"                     Makefile       &&
sedit  "s/bin/games/"                    Makefile       &&
make_single                                             &&
make  SDATADIR=${INSTALL_ROOT}/usr/share/games/ssystem
