(

  prepare_install                                             &&

  if  !  [  -d  ${INSTALL_ROOT}/usr/share/games/AlephOne  ];  then
    mkdir  -p  ${INSTALL_ROOT}/usr/share/games/AlephOne
  fi                                                          &&

  cp  -a  *  ${INSTALL_ROOT}/usr/share/games/AlephOne

) > $C_FIFO 2>&1
