patch  -p1  <  ${SCRIPT_DIRECTORY}/qt.patch    &&
patch  -p1  <  ${SCRIPT_DIRECTORY}/path.patch  &&
export QTDIR=/usr                              &&

./configure                                    &&
make
