diff -urpN kaf.old/Makefile kaf/Makefile
--- kaf.old/Makefile    2003-12-11 19:08:27.772434848 -0800
+++ kaf/Makefile        2003-12-11 19:09:08.550235680 -0800
@@ -16,7 +16,7 @@ CFLAGS   = -pipe -Wall -W -march=athlon-
 CXXFLAGS = -pipe -Wall -W -march=athlon-xp -mmmx -mfpmath=sse -msse -m3dnow -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED
 LEXFLAGS =
 YACCFLAGS= -d
-INCPATH  = -I/usr/share/qt/mkspecs/default -I. -I$(QTDIR)/include
+INCPATH  = -I/usr/share/qt/mkspecs/default -I. -I$(QTDIR)/include/qt
 LINK     = g++
 LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib
 LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
