(

  prepare_install                          &&
  mkdir  -p  /usr/share/games/FlightGear   &&
  cd  ${SOURCE_DIRECTORY}/data             &&
  cp  -rv  *  /usr/share/games/FlightGear

) > ${C_FIFO} 2>&1
