  ./configure  --prefix=${INSTALL_ROOT}/usr/			\
               --exec-prefix=${INSTALL_ROOT}/usr/               \
               --sysconfdir=${INSTALL_ROOT}/etc/                \
               --localstatedir=${INSTALL_ROOT}/var/             \
               ${OPTS}                                          &&
  jam
