invoke_gcc                                            &&

./configure --prefix=${INSTALL_ROOT}/usr              \
            --bindir=${INSTALL_ROOT}/usr/games        \
           --datadir=${INSTALL_ROOT}/usr/share/games  \
        --sysconfdir=${INSTALL_ROOT}/etc              \
     --localstatedir=${INSTALL_ROOT}/var/games        \
            --mandir=${INSTALL_ROOT}/usr/share/man    \
           --infodir=${INSTALL_ROOT}/usr/share/info   \
                     $OPTS                            &&
make
