if   [[  $FREECIV_CLIENT  ==  "xaw" ]]; then
OPTS="--with-xaw3d $OPTS"
fi                                     &&
OPTS="--enable-client=$FREECIV_CLIENT  \
      $FREECIV_OPTS                    \
      $OPTS"                           &&
default_games_build
