if   [[  $FREECIV_CLIENT  ==  "xaw" ]]; then
  OPTS="--enable-client=xaw --with-xaw3d $OPTS"
fi  &&

OPTS="--disable-dependency-tracking  \
      $FREECIV_OPTS                  \
      $OPTS"                         &&
default_games_build
