./configure --prefix=${INSTALL_ROOT}/usr             \
            --bindir=${INSTALL_ROOT}/usr/games       \
        --sysconfdir=${INSTALL_ROOT}/etc             \
     --localstatedir=${INSTALL_ROOT}/var             \
            --mandir=${INSTALL_ROOT}/usr/share/man   \
           --infodir=${INSTALL_ROOT}/usr/share/info  \
                     $OPTS                           &&
make
