cd mk/linux                                          &&
# default_games_build
OPTS="$OPTS --bindir=${INSTALL_ROOT}/usr/games       \
           --datadir=${INSTALL_ROOT}/usr/share/games \
     --localstatedir=${INSTALL_ROOT}/var/games"      &&
./configure ${OPTS}                                  &&
jam
