./configure  --build=$BUILD                         \
            --prefix=${INSTALL_ROOT}/usr            \
            --bindir=${INSTALL_ROOT}/usr/games      \
            --mandir=${INSTALL_ROOT}/usr/share/man  \
        --sysconfdir=${INSTALL_ROOT}/etc            \
                     $OPTS                          &&
make
