cd ${SOURCE_DIRECTORY}/${SPELL}-${VERSION}-src  &&
make                             &&
cd build                         &&
cd release*                      &&
cp -p *.* ${SOURCE_DIRECTORY}                &&
cd ../..                         &&
rm -rf ${SPELL}-${VERSION}-src               &&
cd ${BUILD_DIRECTORY}
