true                                         &&
DATA=${INSTALL_ROOT}/usr/share/games/duke3d  &&
cd $SOURCE_DIRECTORY/source/buildengine      &&
make                                         &&
cd $SOURCE_DIRECTORY/source                  &&
make                                         &&
strip duke3d
