CFLAGS=${CFLAGS/-fPIC}                    &&
CFLAGS=${CFLAGS/-DPIC}                    &&
CXXFLAGS=${CXXFLAGS/-fPIC}                &&
CXXFLAGS=${CXXFLAGS/-DPIC}                &&
sh  build.sh  uqm  reprocess_config       &&
sh  build.sh  uqm
